web/aivle0205/accounts/urls.py
from django.urls import path,include
from . import views
from .views import AuthSmsSendView,SMSVerificationConfirmView
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('update/',views.update, name='update'),
    path('sms/', AuthSmsSendView.as_view(), name='send_sms'),
    path('phone_verification/',views.phone_verification,name='phone_verification'),
    path('sms/check/', SMSVerificationConfirmView.as_view(), name='snscheck'),
    path('logout/', views.logout_view, name='logout'),
    path('delete/', views.delete, name='delete'),
]

web/aivle0205/aivle0205/urls.py
# urls.py

"""
URL configuration for aivle0205 project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
   
    path('main/', views.main, name='main'),

    
    

    path('post/', include('post.urls')),
    path('repair_cost/', include('repair_cost.urls')),
    path('fault_ratio/', include('fault_ratio.urls')),

    
    path('contact/',include('contact.urls')),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name = 'about'),
    path('account/', views.account, name='account'),
    
    path('test/', views.test_view, name='test'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

web/aivle0205/contact/urls.py
from django.urls import path
from .views import send_email
from . import views
app_name = 'contact'
urlpatterns = [
    path('', views.send_email, name='send_email'),
    
]

web/aivle0205/fault_ratio/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'fault_ratio'
urlpatterns = [
    path('', views.index, name="index"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/aivle0205/post/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/craete/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    
    # path('reply/create/<int:answer_id>/', views.reply_create, name='reply_create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/aivle0205/repair_cost/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'repair_cost'
urlpatterns = [
    path("", views.index, name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/aivle0205/contact/models.py
from django.db import models

# Create your models here.

web/aivle0205/contact/forms.py
from django import forms

class EmailForm(forms.Form):
    name = forms.CharField(label='Name', max_length=100)
    email = forms.EmailField(label='Email')
    phone = forms.CharField(label='Phone', max_length=100)
    message = forms.CharField(label='Message', widget=forms.Textarea)

web/aivle0205/contact/views.py
from django.contrib import messages
from django.core.mail import EmailMessage
from django.shortcuts import render
from django.views import View

from .forms import EmailForm

def send_email(request):
    if request.method == "POST":
        form = EmailForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            message = form.cleaned_data['message']
            
            subject = f"새로운 이메일이 도착했습니다: {name}"
            email_body = f"보낸 사람: {name}\n이메일: {email}\n전화번호: {phone}\n\n{message}"
            to_email = ['asdfgyuio123@naver.com']

            EmailMessage(subject=subject, body=email_body, to=to_email).send()
            return render(request, 'contact.html', {'success_message': '이메일이 성공적으로 전송되었습니다!'})
        else:
            return render(request, 'contact.html', {'form': form, 'error_message': '입력한 정보가 올바르지 않습니다.'})
    else:
        form = EmailForm()
        return render(request, 'contact.html', {'form': form})

web/aivle0205/templates/about.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>about us</title>
<link href="{% static 'css/about.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<script src="{% static 'js/nav.js' %}"></script>
</head>
<body>
    <!-- 네비바 -->
    <nav class="nav scroll-hidden">
      <ul class="menu">
        <li>
          <a href="{% url 'index' %}">Home</a>
        </li>
        <li><a href="#" onClick="jumpToID(event, 'service')">Service+</a>
          <ul class="submenu">
            <li><a href="{% url 'repair_cost:index' %}">Repair Cost</a></li>
            <li><a href="{% url 'fault_ratio:index' %}">Fault Ratio</a></li>
          </ul>
        </li>
        <li><a href="#" onClick="jumpToID(event, 'support')">Support+</a>
          <ul class="submenu">
            <li><a href="{% url 'post:index' %}">Post Board</a></li>
            <li><a href="{% url 'contact' %}">Contact Us</a></li>
          </ul>
        </li>
        {% if user.is_authenticated %}
        <li><a href="#" onClick="jumpToID(event, 'support')">Login</a>
          <ul class="submenu">
            <li><a href="{% url 'logout' %}">Logout</a></li>
            <li><a href="{% url 'accounts:update' %}">update</a></li>
          </ul>
        </li>
        {% else %}
        <li><a href="{% url 'login' %}">Login</a></li>{% endif %}</li>
        
        <li><a href="{% url 'about' %}">About Us</a></li>
      </ul>
    </nav>

    <main>
        <section class="bg01">
            <div class="container01"></div>
            <div class="container01">
                <div>
                    <div id="title" style="text-align: center;">
                        "SURISURI CARSURI"
                    </div>
                    <div class="spacer"></div>
                    <div id="team-title">
                        TEAM
                    </div>
                </div>
            </div>
            <div class="container01"></div>
        </section>
    </main>
</body>


<!--프로필 시작-->
<section class="profile-section">
  <div class="profile-container">
    <div class="profile-row">
      <div class="profile-item" onclick="showProfilePopup('차승현', '{% static 'image/profile/승현님.png' %}', 'AI');">
        <div class="profile-info">
          <img src="{% static 'image/profile/승현님.png' %}" alt="차승현">
          <div class="profile-name">차승현</div>
        </div>
      </div>
      <div class="profile-item" onclick="showProfilePopup('신원석', '{% static 'image/profile/원석님.png' %}', 'AI&Backend')">
        <div class="profile-info">
          <img src="{% static 'image/profile/원석님.png' %}" alt="신원석">
            <div class="profile-name">신원석</div>
        </div>
      </div>
      <div class="profile-item" onclick="showProfilePopup('이동우', '{% static 'image/profile/동우님.png' %}', 'Frontend')">
              <div class="profile-info">
                <img src="{% static 'image/profile/동우님.png' %}" alt="이동우">
                <div class="profile-name">이동우</div>
              </div>
            </div>
          </div>
          <div class="profile-row">
            <div class="profile-item" onclick="showProfilePopup('김석원', '{% static 'image/profile/석원님.png' %}', 'Backend')">
              <div class="profile-info">
                <img src="{% static 'image/profile/석원님.png' %}" alt="김석원">
                <div class="profile-name">김석원</div>
              </div>
            </div>
            <div class="profile-item" onclick="showProfilePopup('박준수', '{% static 'image/profile/준수님.png' %}', 'Backend&AI')">
              <div class="profile-info">
                <img src="{% static 'image/profile/준수님.png' %}" alt="박준수">
                <div class="profile-name">박준수</div>
              </div>
            </div>
            <div class="profile-item" onclick="showProfilePopup('김창현', '{% static 'image/profile/창현님.png' %}', 'Frontend')">
              <div class="profile-info">
                <img src="{% static 'image/profile/창현님.png' %}" alt="김창현">
                <div class="profile-name">김창현</div>
              </div>
            </div>
            <div class="profile-item" onclick="showProfilePopup('김현아', '{% static 'image/profile/김현아.png' %}', 'Frontend')">
              <div class="profile-info">
                <img src="{% static 'image/profile/김현아.png' %}" alt="김현아">
                <div class="profile-name">김현아</div>
              </div>
            </div>
          </div>
        </div>
</section>
<!-- 프로필 사진 칸 끝 -->

<!-- 팝업 시작 -->
<div class="modal-wrapper">
    <div class="modal modal-right">
      <div class="head">
        <a class="btn-close trigger" href="#">
          <span class="close-icon">X</span>
        </a>
      </div>
      <div class="content">
        <div class="profile-info">
          <img src="" alt="프로필 이미지" id="popup-profile-image">
          <div class="profile-name" id="popup-profile-name"></div>
          <div class="profile-description" id="popup-profile-description"></div>
        </div>
      </div>
    </div>
</div>
<!-- 팝업 끝 -->
 <!--############## footer ###############-->
 <footer class="bg04" id="footer">
		
  <div id="bg04-02">AIVLE SCHOOL</div>
  <hr id="bg04-03-hr">

  <div class="bg04-03">
      <ul>
          <li>
              <!--###### 이용약관 ######-->
              <a href="{% url 'test' %}" onclick="goPrivacy(event)" class = "bg04-03-li">개인정보 처리방침 이용약관</a>
              <script>
                  function goPrivacy(event) {
                      event.preventDefault();  // 링크 클릭 시 기본 동작(페이지 이동)을 막음
                      // 팝업 창 열기
                      window.open('/test/', '_blank', 'width=600,height=500,scrollbars=yes');
                  }
              </script>
              <!--##############-->
          </li>
          <li><a href="{% url 'contact' %}" class="bg04-03-li">Contact Us</a></li>
          <li><a href="{% url 'about' %}" class="bg04-03-li">About Us</li>
      </ul>
  </div>
  <footer class="bg04-04">
      <div id="bg04-04-01"></div>
      <div class="bg04-04-01">Copyright 2023 AIVLE 2-5.</div>
  </footer>
</footer>
</main>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    var scrollPosition = 0;

    function showProfilePopup(name, imageSrc, description) {
      // 스크롤 위치 저장
      scrollPosition = window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop;

      // 프로필 정보를 팝업에 표시하는 함수
      document.getElementById("popup-profile-image").src = imageSrc;
      document.getElementById("popup-profile-name").innerText = name;
      document.getElementById("popup-profile-description").innerText = description;

      // 팝업을 보여주는 동작
      document.querySelector('.modal-wrapper').classList.add('open');
      document.querySelector('.page-wrapper').classList.add('blur-it');

      // 페이지 스크롤 방지
      document.body.style.overflow = 'hidden';
    }

    // 팝업 닫기 버튼 동작
    document.querySelector('.btn-close').addEventListener('click', function() {
      document.querySelector('.modal-wrapper').classList.remove('open');
      document.querySelector('.page-wrapper').classList.remove('blur-it');

      // 페이지 스크롤 허용
      document.body.style.overflow = 'auto';

      // 이전 스크롤 위치로 스크롤 이동
      window.scrollTo(0, scrollPosition);
    });
</script>
</body>
</html>

web/aivle0205/templates/base.html
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- bootstrap link, keep in <head> tag -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/mycss.css' %}" />
	<title>수리수리차수리</title>
</head>

<body id="page-top">
	<div id="container01">
	    <!--#############################################-->
		<nav class="nav scroll-hidden">
			<ul class="menu">
				<li>
					<a href="{% url 'index' %}">Home</a>
				</li>
				<li><a href="#">Service+</a>
				<ul class="submenu">
					<li><a href="{% url 'repair_cost:index' %}">Repair Cost</a></li>
					<li><a href="{% url 'fault_ratio:index' %}">Fault Ratio</a></li>
				</ul></li>
				<li><a href="#">Support+</a>
					<ul class="submenu">
						<li><a href="{% url 'post:index' %}">Post Board</a></li>
						<li><a href="{% url 'contact' %}">Contact Us</a></li>
					</ul></li>
					{% if user.is_authenticated %}
					<li><a href="#" onClick="jumpToID(event, 'support')">account</a>
						<ul class="submenu">
							<li><a href="{% url 'logout' %}">Logout</a></li>
							<li><a href="{% url 'accounts:update' %}">update</a></li>
						</ul>
					</li>
					{% else %}
					<li><a href="{% url 'login' %}">Login</a></li>{% endif %}</li>
				<li><a href="{% url 'about' %}">About Us</a></li>
			</ul>
			</nav>
	<!--#############################################-->

	<main id="main">
		{% block content %}
		{% endblock %}
	</main>
	<footer class="bg04" id="footer">
        <div id="bg04-02">AIVLE SCHOOL</div>
        <hr id="bg04-03-hr">
        <div class="bg04-03">
            <ul>
                <li>
                    <!--###### 이용약관 ######-->
                    <a href="{% url 'test' %}" onclick="goPrivacy(event)" class = "bg04-03-li">개인정보 처리방침 이용약관</a>
                    <script>
                        function goPrivacy(event) {
                            event.preventDefault();  // 링크 클릭 시 기본 동작(페이지 이동)을 막음
                            // 팝업 창 열기
                            window.open('/test/', '_blank', 'width=600,height=500,scrollbars=yes');
                        }
                    </script>
                    <!--##############-->
                </li>
                <li><a href="{% url 'contact' %}" class="bg04-03-li">Contact Us</a></li>
                <li><a href="{% url 'about' %}" class="bg04-03-li">About Us</li>
            </ul>
        </div>
        <footer class="bg04-04">
            <div id="bg04-04-01"></div>
            <div class="bg04-04-01">Copyright 2023 AIVLE 2-5.</div>
        </footer>
</footer>
	
	<a href="#" class="back-to-top" onClick="jumpToID(event, 'page-top')"><img src="{% static 'image/up.png' %}" alt="위로아이콘" id="back-to-top-button"></a>
	<a href="#" class="top-to-back" onClick="jumpToFoot(event, 'footer')"><img src="{% static 'image/down.png' %}" alt="아래로아이콘" id="top-to-back-button"></a>
	<!-- bootstrap js, insert before </body> -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
		crossorigin="anonymous"></script>
	<script src="{% static 'js/nav.js' %}"></script>
</body>
</html>

web/aivle0205/templates/contact.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
            <meta
                name="viewport"
                content="width=device-width, initial-scale=1, shrink-to-fit=yes">
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/css?family=Jeju+Gothic">
                    <link
                        rel="stylesheet"
                        href="https://fonts.googleapis.com/css?family=Junckey+One">
                        <link
                            rel="stylesheet"
                            href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
                            integrity="sha384-DZg+u82t7q7bPQ4zrZAYLzQanOQTfz1XL8t6OGI7GKsHS+jMqnuJ4XjLGYQK+oiF"
                            crossorigin="anonymous">
                            <script
                                src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"
                                integrity="sha384-cmZv6n4rYPO8/3qFDJxC9uQBUqMEeK6IdTPxZtQ7to1dZf/r4Edp8Hq94vSwTTSk"
                                crossorigin="anonymous"></script>
                            <!-- Required meta tags -->
                            <title>contact us</title>
                            <link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}"/>

                        </head>
                        <body>
                            <div id="container01">
                                <!--################navi###################-->
                                <nav class="nav scroll-hidden">
                                    <ul class="menu">
                                            <li>
                                                <a href="{% url 'index' %}">Home</a>
                                            </li>
                                        <li><a href="#">Service+</a>
                                        <ul class="submenu">
                                            <li><a href="{% url 'repair_cost:index' %}">Repair Cost</a></li>
                                            <li><a href="{% url 'fault_ratio:index' %}">Fault Ratio</a></li>
                                        </ul></li>
                                        <li><a href="#">Support+</a>
                                            <ul class="submenu">
                                                <li><a href="{% url 'post:index' %}">Post Board</a></li>
                                                <li><a href="{% url 'contact' %}">Contact Us</a></li>
                                            </ul></li>
                                            {% if user.is_authenticated %}
                                            <li><a href="#" onClick="jumpToID(event, 'support')">account</a>
                                                <ul class="submenu">
                                                    <li><a href="{% url 'logout' %}">Logout</a></li>
                                                    <li><a href="{% url 'accounts:update' %}">update</a></li>
                                                </ul>
                                            </li>
                                            {% else %}
                                            <li><a href="{% url 'login' %}">Login</a></li>{% endif %}</li>
                                        <li><a href="{% url 'about' %}">About Us</a></li>
                                    </ul>
                                    </nav>
                                <!--################navi###################-->
                                <main>
                                    <section class="bg01">
                                        <div class="left-section">
                                            <div class="container01">
                                                <div>
                                                    <div id="title">
                                                        contact
                                                    </div>
                                                    <div id="subtitle">
                                                        Please provide your
                                                        <br>
                                                            contact infromation
                                                        </div>
                                                    </div>
                                                    <div id="form">
                                                        <form method="post" action="{% url 'contact:send_email' %}">
                                                            {% csrf_token %}
                                                            <div class="form-field">
                                                                <label for="name" class="form-label">Name</label>
                                                                <input type="text" id="name" class="form-input" name='name'>
                                                            </div>
                                                            <div class="form-field">
                                                                <label for="email" class="form-label">Email</label>
                                                                <input type="email" id="email" class="form-input" name='email'>
                                                            </div>
                                                            <div class="form-field">
                                                                <label for="phone" class="form-label">Phone</label>
                                                                <input type="tel" id="phone" class="form-input" name='phone'>
                                                            </div>
                                                            <div class="form-field">
                                                                <label for="message" class="form-label">Message</label>
                                                                <div class="form-textarea-container" >
                                                                    <textarea id="message" placeholder="MESSAGE" class="form-textarea" name='message'></textarea>
                                                                </div>
                                                            </div>
                                                            <div class="form-submit">
                                                                <button type="Submit">submit</button>
                                                            </div>
                                                        </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="right-section">
                                                            <div class="address-title">Address</div>
                                                            <div class="address-description">
                                                                90, Buljeong-ro,<br>Bundang-gu,
                                                                    <br>Seongnam-si,
                                                                        <br>Gyeonggi-do,
                                                                            <br>Republic of Korea
                                                                            </div>
                                                                        </section>

                                                                        <!--############## footer ###############-->
                                                                        <footer class="bg04" id="footer">
		
                                                                            <div id="bg04-02">AIVLE SCHOOL</div>
                                                                            <hr id="bg04-03-hr">
                                                                    
                                                                            <div class="bg04-03">
                                                                                <ul>
                                                                                    <li>
                                                                                        <!--###### 이용약관 ######-->
                                                                                        <a href="{% url 'test' %}" onclick="goPrivacy(event)" class = "bg04-03-li">개인정보 처리방침 이용약관</a>
                                                                                        <script>
                                                                                            function goPrivacy(event) {
                                                                                                event.preventDefault();  // 링크 클릭 시 기본 동작(페이지 이동)을 막음
                                                                                                // 팝업 창 열기
                                                                                                window.open('/test/', '_blank', 'width=600,height=500,scrollbars=yes');
                                                                                            }
                                                                                        </script>
                                                                                        <!--##############-->
                                                                                    </li>
                                                                                    <li><a href="{% url 'contact' %}" class="bg04-03-li">Contact Us</a></li>
                                                                                    <li><a href="{% url 'about' %}" class="bg04-03-li">About Us</li>
                                                                                </ul>
                                                                            </div>
                                                                            <footer class="bg04-04">
                                                                                <div id="bg04-04-01"></div>
                                                                                <div class="bg04-04-01">Copyright 2023 AIVLE 2-5.</div>
                                                                            </footer>
                                                                      </footer>
                                                                    </main>
                                                                    <script>
                                                                        {% if success_message %}
                                                                            showMessage('{{ success_message }}', 'success');
                                                                        {% endif %}
                                                                
                                                                        function showMessage(message, messageType) {
                                                                            const messageElement = document.createElement('div');
                                                                            messageElement.textContent = message;
                                                                            messageElement.classList.add(messageType);
                                                                            messageElement.classList.add('green'); 
                                                                            document.getElementById('form').appendChild(messageElement);
                                                                        }
                                                                    </script>
                                                                    
                                                                    <style>
                                                                        .success {
                                                                            color: green;
                                                                        }
                                                                    </style>
                                                                </body>
                                                            </html>

web/aivle0205/templates/main.html
<form method="post" action="{% url 'logout' %}">
<h1>메인</h1>

<ul>
  <li><a href="{% url 'main' %}">홈</a></li>
  <!-- 기타 메뉴 항목 -->
  {% if user.is_authenticated %}
    <li><a href="{% url 'accounts:update' %}">회원 정보 수정</a></li>
    <li>
      <p>{{ user.username }} 님 환영합니다.</p>
        {% csrf_token %}
        <button type="submit" value='logout'>로그아웃</button>  <!-- 로그아웃 버튼 -->
      </form>
    </li>
    <li><a href="{% url 'post:index' %}">게시판</a></li>
  {% else %}
    <li><a href="{% url 'login' %}">로그인</a></li>  <!-- 로그인 버튼 -->
    <li><a href="{% url 'accounts:signup' %}">회원가입</a></li>
    <li><a href="{% url 'post:index' %}">게시판</a></li>
  {% endif %}
</ul>