web/aivle0205/accounts/urls.py
from django.urls import path,include
from . import views
from .views import AuthSmsSendView,SMSVerificationConfirmView
app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('update/',views.update, name='update'),
    path('sms/', AuthSmsSendView.as_view(), name='send_sms'),
    path('phone_verification/',views.phone_verification,name='phone_verification'),
    path('sms/check/', SMSVerificationConfirmView.as_view(), name='snscheck'),
    path('logout/', views.logout_view, name='logout'),
    path('delete/', views.delete, name='delete'),
]

web/aivle0205/aivle0205/urls.py
# urls.py

"""
URL configuration for aivle0205 project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name='index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
   
    path('main/', views.main, name='main'),

    
    

    path('post/', include('post.urls')),
    path('repair_cost/', include('repair_cost.urls')),
    path('fault_ratio/', include('fault_ratio.urls')),

    
    path('contact/',include('contact.urls')),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name = 'about'),
    path('account/', views.account, name='account'),
    
    path('test/', views.test_view, name='test'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

web/aivle0205/fault_ratio/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'fault_ratio'
urlpatterns = [
    path('', views.index, name="index"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/aivle0205/post/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/craete/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', views.question_delete, name='question_delete'),
    
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # path('answer/modify/<int:answer_id>/', views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', views.answer_delete, name='answer_delete'),
    
    # path('reply/create/<int:answer_id>/', views.reply_create, name='reply_create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/aivle0205/repair_cost/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'repair_cost'
urlpatterns = [
    path("", views.index, name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/aivle0205/post/models.py
from django.db import models
from accounts.models import User

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to='images/post', null=True)
    content = models.TextField(null=False)
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)
    def __str__(self):
        return self.title

class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField(null=False)
    create_date = models.DateTimeField(auto_now_add=True)
    modify_date = models.DateTimeField(null=True, blank=True)
    parent_answer = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.content
    
    

web/aivle0205/post/forms.py
from django import forms
from post.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'image', 'content']
        labels = {
            'title': 'Title',
            'image': 'Image Upload',
            'content': 'Content',
        }
        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

web/aivle0205/post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Question, Answer
from .forms import QuestionForm, AnswerForm
from django.utils import timezone
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from datetime import datetime

def index(req):
    page = req.GET.get('page', '1')
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    today = datetime.today().date()
    context = {'question_list': page_obj, 'today': today}
    return render(req, 'post/question_list.html', context)

def detail(req, question_id):
    question = get_object_or_404(Question, pk=question_id)
    today = datetime.today().date()
    context = {'question': question, 'today': today}
    return render(req, 'post/question_detail.html', context)

@login_required(login_url='accounts:login')
def question_create(req):
    if req.method == 'POST':
        form = QuestionForm(req.POST)
        if form.is_valid():
            question = form.save(commit=False)
            if req.FILES:
                question.image = req.FILES['image']
            question.user = req.user
            question.save()
            return redirect('post:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(req, 'post/question_form.html', context)

@login_required(login_url='accounts:login')
def question_modify(req, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if req.user != question.user:
        messages.error(req, '수정권한이 없습니다')
        return redirect('post:detail', question_id=question.id)
    
    if req.method == 'POST':
        form = QuestionForm(req.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            if req.FILES:
                question.image = req.FILES['image']
            question.save()
            return redirect('post:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form, 'question': question,}
    return render(req, 'post/question_form.html', context)

@login_required(login_url='accounts:login')
def question_delete(req, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if req.user != question.user:
        messages.error(req, '삭제권한이 없습니다')
        return redirect('post:detail', question_id=question.id)
    question.delete()
    return redirect('post:index')

@login_required(login_url='accounts:login')
def answer_create(req, question_id):
    question = get_object_or_404(Question, pk=question_id)
    answer = Answer(question=question,
                    content=req.POST.get('content'), user=req.user)
    answer.save()
    return redirect('post:detail', question_id=question.id)

# @login_required(login_url='common:login')
# def answer_modify(req, answer_id):
#     answer = get_object_or_404(Answer, pk=answer_id)
#     # if req.user != answer.user:
#     #     messages.error(req, '수정권한이 없습니다')
#     #     return redirect('pybo:detail', question_id=answer.question.id)
#     if req.method == "POST":
#         form = AnswerForm(req.POST, instance=answer)
#         if form.is_valid():
#             answer = form.save(commit=False)
#             answer.modify_date = timezone.now()
#             answer.save()
#             return redirect('post:detail', question_id=answer.question.id)
#     else:
#         form = AnswerForm(instance=answer)
#     context = {'answer': answer, 'form': form}
#     return render(req, 'post/answer_form.html', context)

@login_required(login_url='accounts:login')
def answer_delete(req, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if req.user != answer.user:
        messages.error(req, '삭제권한이 없습니다')
        return redirect('post:detail', question_id=answer.question.id)
    answer.delete()
    return redirect('post:detail', question_id=answer.question.id)

# @login_required(login_url='accounts:login')
# def reply_create(req, answer_id):
#     answer = get_object_or_404(Answer, pk=answer_id)
#     question = get_object_or_404(Question, pk=answer.question.id)

web/aivle0205/post/templates/post/answer_form.html
<form method="post">
    {% csrf_token %}
    {% comment %} {% include "form_errors.html" %} {% endcomment %}
    <label for="content" class="form-label">답변내용</label>
    <textarea name="content" id="content"
                rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    <button type="submit" class="btn btn-primary">저장하기</button>
</form>

web/aivle0205/post/templates/post/question_detail.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">


<title>웹 페이지의 구성 요소</title>
<link href="{% static 'css/dw_post_result.css' %}" rel="stylesheet" type="text/css">

<script>
    var container = document.querySelector('.container');
    var nav = document.querySelector('nav');

    container.addEventListener('mouseenter', function () {
        nav.classList.add('nav-hover');
    });

    container.addEventListener('mouseleave', function () {
        nav.classList.remove('nav-hover');
    });

    function myFunction(msg) {
        alert(msg);
    }
</script>

</head>

<body>
<!--#############################################-->
<div id="container01">
        <!--################navi###################-->
        <nav class="nav scroll-hidden">
            <ul class="menu">
                    <li>
                        <a href="{% url 'index' %}">Home</a>
                    </li>
                <li><a href="#">Service+</a>
                <ul class="submenu">
                    <li><a href="{% url 'repair_cost:index' %}">Repair Cost</a></li>
                    <li><a href="{% url 'fault_ratio:index' %}">Fault Ratio</a></li>
                </ul></li>
                <li><a href="#">Support+</a>
                    <ul class="submenu">
                        <li><a href="{% url 'post:index' %}">Post Board</a></li>
                        <li><a href="{% url 'contact' %}">Contact Us</a></li>
                    </ul></li>
                    {% if user.is_authenticated %}
                    <li><a href="#" onClick="jumpToID(event, 'support')">account</a>
                        <ul class="submenu">
                            <li><a href="{% url 'logout' %}">Logout</a></li>
                            <li><a href="{% url 'accounts:update' %}">update</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>{% endif %}</li>
                <li><a href="{% url 'about' %}">About Us</a></li>
            </ul>
            </nav>
        <!--################navi###################-->

<main>
<!-- <section class="'bg01"> -->
    <!-- <div class="container01"></div> -->

    <!-- <div class="container01"></div> -->
<!-- </section>과실 비율을 출력 -->

    <section class="bg02">
        <div class="bg02-01">
            {% comment %} <div id="title">
            "Post Board"
            </div> {% endcomment %}
        </div>
        <div class="container01">
        </div>
        <div class=" bg02 bg02-left">
            <div class="bg02-box01">
                <p id="bg02-title">{{ question.title }}</p>
                <p id="bg02-text">
                    {{ question.content }}
                </p>
            </div>
        </div>
        
        <div class="bg02 bg02-right">
            <div class="bg02-box02">
                {% if question.image %}
                    <img id="bg02-img" src="{{question.image.url}}">
                {% else%}
                    <img id="bg02-img" src="{%static 'assets/images/black5.jpg' %}">
                {% endif %}
            </div>
                <img class="bg-cover" src="{%static 'assets/images/img1.png' %}">
        </div>
    </section>

    <section class="bg2_5">
        <div class="bg2_5-01">
            <table>
                <thead>
                <tr>
                    <th>ID</th><th>User Comment</th><th>Date</th><th style="width:50px"></th>
                </tr>
                </thead>
                <tbody>
                {% for answer in question.answer_set.all %}
                    {% if answer.parent_answer == null %}
                        <tr>
                            <td>{{ answer.user }}</td>
                            <td>{{ answer.content }}</td>
                            {% if answer.create_date.date == today %}
                                <td>{{answer.create_date|date:'H:i'}}</td>
                            {% else %}
                                <td>{{answer.create_date|date:'y.m.d'}}</td>
                            {% endif %}
                            <td>{% if request.user == answer.user%}<a href="{% url 'post:answer_delete' answer.id  %}">삭제</a>{% endif %}</td>
                        </tr>
                        {% for reply in answer.answer_set.all %}
                            <tr>
                                <td>{{ reply.user }}</td>
                                <td>{{ reply.content }}</td>
                                <td>{{ reply.create_date }}</td>
                                <td>{% if user.is_authenticated %}<a href="{% url 'post:answer_delete' reply.id  %}">삭제</a>{% endif %}</td>
                            </tr>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </section>

<!--##########################################-->
    <section class="bg03">
        <form class="bg03-01" method="POST" {% if user.is_authenticated %}action='{% url 'post:answer_create' question.id %}'{% endif %}>
            {% csrf_token %}
            <div id="bg03-textarea">
                <div><label for="content" class="form-label" id='bg03-comment'>Comment</label><div>
                <br>
                <textarea class="form-control bg03-textarea" name="content" id="content"></textarea>
            </div>
            <div>
                <button id="bg03-submit"{% if user.is_authenticated %}type="submit"{% else %}onclick="myFunction('로그인 후 이용하세요!')"
                {% endif %}>작성하기</button>
            </div>
        </form>
    </section>

    <br>
    <br>
    <div>
        {% if request.user == question.user %}
        <button id="bg03-submit" type="submit" onclick="location.href='{% url 'post:question_modify' question.id %}' ">수정</button>
        &nbsp;
        <button id="bg03-submit" type="submit" onclick="location.href='{% url 'post:question_delete' question.id %}' ">삭제</button>
        {% endif %}
    </div>
</main>

<!--##########################################-->
<footer class="bg04" id="footer">
		
    <div id="bg04-02">AIVLE SCHOOL</div>

    {% comment %} <div class="bg04-02">
        <img class='bg04-02 bg04-02-img' src="{% static 'assets/images/black5.jpg' %}">
        <img class='bg04-02 bg04-02-img' src="{% static 'assets/images/black5.jpg' %}">
        <img class='bg04-02 bg04-02-img' src="{% static 'assets/images/black5.jpg' %}">
        <img class='bg04-02 bg04-02-img' src="{% static 'assets/images/black5.jpg' %}">
        <img class='bg04-02 bg04-02-img' src="{% static 'assets/images/black5.jpg' %}">
        <img class='bg04-02 bg04-02-img' src="{% static 'assets/images/black5.jpg' %}">
        <img class='bg04-02 bg04-02-img' src="{% static 'assets/images/black5.jpg' %}">
    </div> {% endcomment %}
    <hr id="bg04-03-hr">

    <div class="bg04-03">
        <ul>
            <li>
                <!--###### 이용약관 ######-->
                <a href="{% url 'test' %}" onclick="goPrivacy(event)" class = "bg04-03-li">개인정보 처리방침 이용약관</a>
                <script>
                    function goPrivacy(event) {
                        event.preventDefault();  // 링크 클릭 시 기본 동작(페이지 이동)을 막음
                        // 팝업 창 열기
                        window.open('/test/', '_blank', 'width=600,height=500,scrollbars=yes');
                    }
                </script>
                <!--##############-->
            </li>
            <li><a href="{% url 'contact' %}" class="bg04-03-li">Contact Us</a></li>
            <li><a href="{% url 'about' %}" class="bg04-03-li">About Us</li>
        </ul>
    </div>
    <footer class="bg04-04">
        <div id="bg04-04-01"></div>
        <div class="bg04-04-01">Copyright 2023 AIVLE 2-5.</div>
    </footer>
</footer>
</div>
</body>
</html>

web/aivle0205/post/templates/post/question_list.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Post Board</title>
    <link href="{%static 'css/dw_post.css' %}" rel="stylesheet" type="text/css">

    <script>
        var container = document.querySelector('.container');
        var nav = document.querySelector('nav');

        container.addEventListener('mouseenter', function () {
            nav.classList.add('nav-hover');
        });

        container.addEventListener('mouseleave', function () {
            nav.classList.remove('nav-hover');
        });

        function myFunction(msg) {
            alert(msg);
        }
    </script>

</head>

<body>
<!--#############################################-->
<div id="container01">
    <!--################navi###################-->
    <nav class="nav scroll-hidden">
        <ul class="menu">
                <li>
                    <a href="{% url 'index' %}">Home</a>
                </li>
            <li><a href="#">Service+</a>
            <ul class="submenu">
                <li><a href="{% url 'repair_cost:index' %}">Repair Cost</a></li>
                <li><a href="{% url 'fault_ratio:index' %}">Fault Ratio</a></li>
            </ul></li>
            <li><a href="#">Support+</a>
                <ul class="submenu">
                    <li><a href="{% url 'post:index' %}">Post Board</a></li>
                    <li><a href="{% url 'contact' %}">Contact Us</a></li>
                </ul></li>
                {% if user.is_authenticated %}
                <li><a href="#" onClick="jumpToID(event, 'support')">account</a>
                    <ul class="submenu">
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                        <li><a href="{% url 'accounts:update' %}">update</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>{% endif %}</li>
            <li><a href="{% url 'about' %}">About Us</a></li>
        </ul>
        </nav>
    <!--################navi###################-->

    <main>
        <section class="bg02">
            <div class="container01"></div>
            <div class=" bg02 bg02-left">
                    <div id="bg02-title">
                    Post Board
                </div>
                <div class="bg02-text">
                    You can view the history of users <br>
                    who have used our services in the past,<br> 
                    or your own history.<br> 
                    Please refer to this page to start using our services.
                </div>
            </div>
            <div class="bg02 bg02-right">
                <img class="bg-cover" src="{%static 'assets/images/img1.png' %}">
            </div>
        </section>

        <section class="bg2_5">
            <div class="bg2_5-01">
                <table>
                    <thead>
                    <tr>
                        <th>No</th><th>Accident Report</th><th>User ID</th><th>Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% load post_filter %}
                    {% if question_list %}
                        {% for question in question_list %}
                            <tr>
                                <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
                                <td>
                                    <a class='question_title' href="{% url 'post:detail' question.id %}">{{ question.title }}
                                    {% if question.answer_set.count > 0 %}
                                        &nbsp;({{question.answer_set.count}})
                                    {% endif %}
                                    {% if question.modify_date %}
                                        &nbsp;(수정됨)
                                    {% endif %}
                                    </a>
                                </td>
                                <td>{{question.user}}</td>
                                {% if question.create_date.date == today %}
                                    <td>{{question.create_date|date:'H:i'}}</td>
                                {% else %}
                                    <td>{{question.create_date|date:'y.m.d'}}</td>
                                {% endif %}
                            <tr>
                        {% endfor %}
                    {% else %}
                        <tr> <td></td><td>글이 없습니다.</td><td></td><td></td> </tr>
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </section>
        <div class="bg2_5-02">
            <button id="submit" type="button" 
            onclick={% if user.is_authenticated %}"location.href='{% url 'post:question_create' %}'"{% else %}"myFunction('로그인 후 이용하세요!')"
            {% endif %}>
            글 작성</button>
        </div>

        <!-- 페이징처리 시작 -->
        <ul class="pagination">
            <!-- 이전페이지 -->
            {% if question_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in question_list.paginator.page_range %}
            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link page-link-num"  href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link page-link-num" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
    </main>

    <!--##########################################-->
    <footer class="bg04" id="footer">
		
        <div id="bg04-02">AIVLE SCHOOL</div>
    
    <hr id="bg04-03-hr">
    
        <div class="bg04-03">
            <ul>
                <li>
                    <!--###### 이용약관 ######-->
                    <a href="{% url 'test' %}" onclick="goPrivacy(event)" class = "bg04-03-li">개인정보 처리방침 이용약관</a>
                    <script>
                        function goPrivacy(event) {
                            event.preventDefault();  // 링크 클릭 시 기본 동작(페이지 이동)을 막음
                            // 팝업 창 열기
                            window.open('/test/', '_blank', 'width=600,height=500,scrollbars=yes');
                        }
                    </script>
                    <!--##############-->
                </li>
                <li><a href="{% url 'contact' %}" class="bg04-03-li">Contact Us</a></li>
                <li><a href="{% url 'about' %}" class="bg04-03-li">About Us</li>
            </ul>
        </div>
        <footer class="bg04-04">
            <div id="bg04-04-01"></div>
            <div class="bg04-04-01">Copyright 2023 AIVLE 2-5.</div>
        </footer>
    </footer>
</div>
</body>
</html>